axon:
  eventhandling:
    processors:
      test:
        mode: tracking
        source: eventBus
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/my-axon-demo?autoReconnect=true"
    driver-class-name: com.mysql.jdbc.Driver
    username: axon
    password: axon
